---
functional:
  - Пользователь должен иметь возможность регистрироваться и авторизироваться
  - Пользователь должен иметь возможность начинать игру с другим пользователем
  - Пользователь должен иметь возможность выбирать язык прораммирования для решения задач
  - Пользователь должен иметь возможность просматривать рейтинговую таблицу
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit: 
  - Возможность выбирать уровень сложности задачи
  - Регулярные обновления и добавление новых задач и функций
  - Автоматическая проверка задач на правильность выполнения
